name: Traack
version: 1.0.2
description: A new Flutter application.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_keyboard_visibility: ^4.0.0
  keyboard_visibility: ^0.5.6

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Bold.ttf
    - family: Circular
      fonts:
        - asset: fonts/CircularStd-Medium.ttf
        - asset: fonts/CircularAir-Light.ttf
          weight: 100
        - asset: fonts/CircularStd-Bold.ttf
          weight: 500


